name:                template-hspec
version:             0.1.0.0
github:              "githubuser/template-hspec"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/template-hspec#readme>

dependencies:
- base >= 4.6 && < 5
- template-haskell
- hspec
- parsec
- haskell-src-meta
- text

library:
  source-dirs: src
  exposed-modules:
  - TemplateHspec  

executables:
  template-hspec-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - template-hspec

tests:
  template-hspec-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - template-hspec
